#!/bin/bash

# Path to the log file generated by the systemd service
LOG_FILE="/run/hardening-audit.log"

# Wait a moment for the desktop to load fully
sleep 3

# Check if the log exists (service ran successfully)
if [ ! -f "$LOG_FILE" ]; then
    notify-send -u critical -i dialog-error "Hardening Audit" "Log file not found! Service may have failed."
    exit 1
fi

# Count result states emitted by hardening-audit.sh
FAIL_COUNT=$(grep -c "\\[FAIL\\]" "$LOG_FILE")
WARN_COUNT=$(grep -c "\\[WARN\\]" "$LOG_FILE")
INFO_COUNT=$(grep -c "\\[INFO\\]" "$LOG_FILE")

if [ "$FAIL_COUNT" -eq 0 ] && [ "$WARN_COUNT" -eq 0 ] && [ "$INFO_COUNT" -eq 0 ]; then
    # PASS: Low priority (transient, green shield icon)
    notify-send -u low -i security-high \
        "System Secured" \
        "Hardening audit passed. All checks green."

elif [ "$FAIL_COUNT" -gt 0 ]; then
    # CRITICAL: Stays on screen until clicked
    notify-send -u critical -i security-low \
        "HARDENING FAILED" \
        "Detected $FAIL_COUNT failures. Run 'sudo hardening-audit' immediately."

elif [ "$WARN_COUNT" -gt 0 ]; then
    # WARNING: Normal priority
    notify-send -u normal -i dialog-warning \
        "Hardening Warnings" \
        "Audit passed with $WARN_COUNT warnings."

elif [ "$INFO_COUNT" -gt 0 ]; then
    # Informational notices: surface them but keep noise low
    notify-send -u low -i dialog-information \
        "Hardening Info" \
        "Audit reported $INFO_COUNT informational notices."

else
    notify-send -u normal -i dialog-question \
        "Audit Result Unknown" \
        "Unexpected audit output state, review log at $LOG_FILE."
fi
